name: .NET

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Parse/ParseSDK.csproj
        VERSION_REGEX: ^\s*<ReleaseVersion>(.*)<\/ReleaseVersion>\s*$
        PACKAGE_NAME: ParseSDK
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - run: |
        echo "Parse-UnityProject/Assets/Scenes.meta" > metaList
        find Parse-UnityProject/Assets/Scenes/ -name \*.meta >> metaList
    - run: mkdir releases
    - name: publish unitypackage
      uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'releases/parse-sdk.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: releases
        name: package
